name: Dockerize and Push to Docker Hub

on: [push]

jobs:
  build:
    name: Build staging
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag applogin:${{ github.sha }}
    - name: Docker Push
      run: docker push applogin:${{ github.sha }}
        
        
